// Hook script: injects session context into CLAUDE.md on SessionStart
// Runs as a local command hook — NO server dependency
// Reads .pan-briefing.md (generated by dream cycle) and injects between PAN-CONTEXT markers

const fs = require('fs');
const path = require('path');

let input = '';
process.stdin.setEncoding('utf-8');
process.stdin.on('data', d => input += d);
process.stdin.on('end', () => {
  try {
    const data = JSON.parse(input);
    const cwd = data.cwd;
    if (!cwd) process.exit(0);

    const claudeMdPath = path.join(cwd, 'CLAUDE.md');
    if (!fs.existsSync(claudeMdPath)) process.exit(0);

    const content = fs.readFileSync(claudeMdPath, 'utf8');
    const startMarker = '<!-- PAN-CONTEXT-START -->';
    const endMarker = '<!-- PAN-CONTEXT-END -->';
    const startIdx = content.indexOf(startMarker);
    const endIdx = content.lastIndexOf(endMarker);
    if (startIdx === -1 || endIdx === -1 || endIdx <= startIdx) process.exit(0);

    // Read living state / briefing file
    const briefingPath = path.join(cwd, '.pan-briefing.md');
    const statePath = path.join(cwd, '.pan-state.md');
    let briefing = '';

    if (fs.existsSync(briefingPath)) {
      briefing = fs.readFileSync(briefingPath, 'utf8').trim();
    }
    if (!briefing && fs.existsSync(statePath)) {
      briefing = fs.readFileSync(statePath, 'utf8').trim();
    }

    if (!briefing) process.exit(0);

    // Build the injection — memory files are NOT included here because
    // Claude Code automatically loads ~/.claude/projects/<slug>/memory/*.md
    // Duplicating them here wastes context tokens
    const fwdCwd = cwd.replace(/\\/g, '/');
    const projectName = path.basename(fwdCwd);

    let injection = `## PAN Session Context\n\n`;
    injection += `This is a fresh session for the "${projectName}" project.\n`;
    injection += `IMPORTANT: The project documentation is at the TOP of this CLAUDE.md file — read it first.\n\n`;
    injection += `**CRITICAL INSTRUCTION:** Your FIRST message to the user MUST be a brief summary of what was discussed recently (from the "Recent Conversation" section below). Start with something like "Last time we were working on..." and list the key topics/issues. The user should never have to ask what they were working on — you tell them immediately.\n\n`;

    // Sanitize briefing — strip any literal PAN-CONTEXT markers that would corrupt future runs
    briefing = briefing.replace(/<!-- PAN-CONTEXT-(START|END) -->/g, '');

    // Append the briefing content (living state + recent conversation)
    injection += briefing + '\n';

    injection += `\n## Instructions\nThis is a fresh session. Your FIRST message to the user MUST be a brief summary of the Recent Conversation above — start with "Last time we were working on..." and list the key topics/issues. The user should NEVER have to ask what they were working on. You tell them immediately, every single time. Then pick up where they left off.\n`;

    // Cap total injection to ~8000 chars to avoid bloating CLAUDE.md
    if (injection.length > 8000) {
      injection = injection.substring(0, 8000) + '\n\n[... context trimmed to reduce CLAUDE.md size ...]\n';
    }

    // Write to CLAUDE.md
    const newContent = content.substring(0, startIdx + startMarker.length) + '\n' +
      injection +
      content.substring(endIdx);
    fs.writeFileSync(claudeMdPath, newContent, 'utf8');
    process.exit(0);
  } catch (e) {
    // Silently fail — don't block Claude startup
    process.exit(0);
  }
});
