
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/tzuri/AppData/Local/Android/Sdk/cmake/3.31.6/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The target system is: Android - 1 - aarch64
      The host system is: Windows - 10.0.26200 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/tzuri/AppData/Local/Android/Sdk/cmake/3.31.6/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/tzuri/AppData/Local/Android/Sdk/cmake/3.31.6/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/tzuri/AppData/Local/Android/Sdk/cmake/3.31.6/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe 
      Build flags: -g;-DANDROID;-fdata-sections;-ffunction-sections;-funwind-tables;-fstack-protector-strong;-no-canonical-prefixes;-D_FORTIFY_SOURCE=2;-Wformat;-Werror=format-security
      Id flags: -c;--target=aarch64-none-linux-android31 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is Clang, found in:
        C:/Users/tzuri/OneDrive/Desktop/PAN/android/llama-lib/.cxx/Release/6w3f313v/arm64-v8a/CMakeFiles/3.31.6/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/tzuri/AppData/Local/Android/Sdk/cmake/3.31.6/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/tzuri/AppData/Local/Android/Sdk/cmake/3.31.6/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/tzuri/AppData/Local/Android/Sdk/cmake/3.31.6/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe 
      Build flags: -g;-DANDROID;-fdata-sections;-ffunction-sections;-funwind-tables;-fstack-protector-strong;-no-canonical-prefixes;-D_FORTIFY_SOURCE=2;-Wformat;-Werror=format-security
      Id flags: -c;--target=aarch64-none-linux-android31 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is Clang, found in:
        C:/Users/tzuri/OneDrive/Desktop/PAN/android/llama-lib/.cxx/Release/6w3f313v/arm64-v8a/CMakeFiles/3.31.6/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/tzuri/AppData/Local/Android/Sdk/cmake/3.31.6/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Users/tzuri/AppData/Local/Android/Sdk/cmake/3.31.6/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/tzuri/OneDrive/Desktop/PAN/android/llama-lib/.cxx/Release/6w3f313v/arm64-v8a/CMakeFiles/CMakeScratch/TryCompile-j0jaeg"
      binary: "C:/Users/tzuri/OneDrive/Desktop/PAN/android/llama-lib/.cxx/Release/6w3f313v/arm64-v8a/CMakeFiles/CMakeScratch/TryCompile-j0jaeg"
    cmakeVariables:
      ANDROID_ABI: "arm64-v8a"
      ANDROID_ARM_MODE: "thumb"
      ANDROID_PIE: "TRUE"
      ANDROID_PLATFORM: "android-31"
      ANDROID_STL: "c++_static"
      ANDROID_TOOLCHAIN: "clang"
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin/clang-scan-deps.exe"
      CMAKE_CXX_COMPILER_TARGET: "aarch64-none-linux-android31"
      CMAKE_C_COMPILER_TARGET: "aarch64-none-linux-android31"
      CMAKE_C_FLAGS: "-g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat "
      CMAKE_C_FLAGS_DEBUG: "-fno-limit-debug-info "
      CMAKE_EXE_LINKER_FLAGS: "-static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments  "
      CMAKE_POSITION_INDEPENDENT_CODE: "TRUE"
      CMAKE_SYSROOT: "C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/tzuri/OneDrive/Desktop/PAN/android/llama-lib/.cxx/Release/6w3f313v/arm64-v8a/CMakeFiles/CMakeScratch/TryCompile-j0jaeg'
        
        Run Build Command(s): C:\\Users\\tzuri\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe -v cmTC_a2840
        [1/2] C:\\Users\\tzuri\\AppData\\Local\\Android\\Sdk\\ndk\\27.0.12077973\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang.exe --target=aarch64-none-linux-android31 --sysroot=C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat   -fPIE   -v -MD -MT CMakeFiles/cmTC_a2840.dir/CMakeCCompilerABI.c.o -MF CMakeFiles\\cmTC_a2840.dir\\CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_a2840.dir/CMakeCCompilerABI.c.o -c C:/Users/tzuri/AppData/Local/Android/Sdk/cmake/3.31.6/share/cmake-3.31/Modules/CMakeCCompilerABI.c
        Android (12027248, based on r522817) clang version 18.0.1 (https://android.googlesource.com/toolchain/llvm-project d8003a456d14a3deb8054cdaa529ffbf02d9b262)
        Target: aarch64-none-linux-android31
        Thread model: posix
        InstalledDir: C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin
         (in-process)
         "C:\\\\Users\\\\tzuri\\\\AppData\\\\Local\\\\Android\\\\Sdk\\\\ndk\\\\27.0.12077973\\\\toolchains\\\\llvm\\\\prebuilt\\\\windows-x86_64\\\\bin\\\\clang.exe" -cc1 -triple aarch64-none-linux-android31 -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=non-leaf -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu generic -target-feature +neon -target-feature +v8a -target-feature +fix-cortex-a53-835769 -target-abi aapcs -debug-info-kind=constructor -dwarf-version=4 -debugger-tuning=gdb -fdebug-compilation-dir=C:/Users/tzuri/OneDrive/Desktop/PAN/android/llama-lib/.cxx/Release/6w3f313v/arm64-v8a/CMakeFiles/CMakeScratch/TryCompile-j0jaeg -v -ffunction-sections -fdata-sections -fcoverage-compilation-dir=C:/Users/tzuri/OneDrive/Desktop/PAN/android/llama-lib/.cxx/Release/6w3f313v/arm64-v8a/CMakeFiles/CMakeScratch/TryCompile-j0jaeg -resource-dir "C:\\\\Users\\\\tzuri\\\\AppData\\\\Local\\\\Android\\\\Sdk\\\\ndk\\\\27.0.12077973\\\\toolchains\\\\llvm\\\\prebuilt\\\\windows-x86_64/lib/clang/18" -dependency-file "CMakeFiles\\\\cmTC_a2840.dir\\\\CMakeCCompilerABI.c.o.d" -MT CMakeFiles/cmTC_a2840.dir/CMakeCCompilerABI.c.o -sys-header-deps -D ANDROID -D _FORTIFY_SOURCE=2 -isysroot C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot -internal-isystem "C:\\\\Users\\\\tzuri\\\\AppData\\\\Local\\\\Android\\\\Sdk\\\\ndk\\\\27.0.12077973\\\\toolchains\\\\llvm\\\\prebuilt\\\\windows-x86_64/lib/clang/18/include" -internal-isystem C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include -internal-externc-isystem C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/aarch64-linux-android -internal-externc-isystem C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include -internal-externc-isystem C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include -Wformat -ferror-limit 19 -stack-protector 2 -fno-signed-char -fgnuc-version=4.2.1 -target-feature +outline-atomics -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_a2840.dir/CMakeCCompilerABI.c.o -x c C:/Users/tzuri/AppData/Local/Android/Sdk/cmake/3.31.6/share/cmake-3.31/Modules/CMakeCCompilerABI.c
        clang -cc1 version 18.0.1 based upon LLVM 18.0.1 default target x86_64-w64-windows-gnu
        ignoring nonexistent directory "C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include"
        ignoring nonexistent directory "C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include"
        #include "..." search starts here:
        #include <...> search starts here:
         C:\\Users\\tzuri\\AppData\\Local\\Android\\Sdk\\ndk\\27.0.12077973\\toolchains\\llvm\\prebuilt\\windows-x86_64/lib/clang/18/include
         C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/aarch64-linux-android
         C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include
        End of search list.
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && C:\\Users\\tzuri\\AppData\\Local\\Android\\Sdk\\ndk\\27.0.12077973\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang.exe --target=aarch64-none-linux-android31 --sysroot=C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments   -v CMakeFiles/cmTC_a2840.dir/CMakeCCompilerABI.c.o -o cmTC_a2840   && cd ."
        FAILED: cmTC_a2840 
        C:\\WINDOWS\\system32\\cmd.exe /C "cd . && C:\\Users\\tzuri\\AppData\\Local\\Android\\Sdk\\ndk\\27.0.12077973\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang.exe --target=aarch64-none-linux-android31 --sysroot=C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments   -v CMakeFiles/cmTC_a2840.dir/CMakeCCompilerABI.c.o -o cmTC_a2840   && cd ."
        Android (12027248, based on r522817) clang version 18.0.1 (https://android.googlesource.com/toolchain/llvm-project d8003a456d14a3deb8054cdaa529ffbf02d9b262)
        Target: aarch64-none-linux-android31
        Thread model: posix
        InstalledDir: C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin
        clang: error: no such file or directory: 'CMakeFiles/cmTC_a2840.dir/CMakeCCompilerABI.c.o'
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/tzuri/AppData/Local/Android/Sdk/cmake/3.31.6/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Check for working C compiler: C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"
    directories:
      source: "C:/Users/tzuri/OneDrive/Desktop/PAN/android/llama-lib/.cxx/Release/6w3f313v/arm64-v8a/CMakeFiles/CMakeScratch/TryCompile-cu7igw"
      binary: "C:/Users/tzuri/OneDrive/Desktop/PAN/android/llama-lib/.cxx/Release/6w3f313v/arm64-v8a/CMakeFiles/CMakeScratch/TryCompile-cu7igw"
    cmakeVariables:
      ANDROID_ABI: "arm64-v8a"
      ANDROID_ARM_MODE: "thumb"
      ANDROID_PIE: "TRUE"
      ANDROID_PLATFORM: "android-31"
      ANDROID_STL: "c++_static"
      ANDROID_TOOLCHAIN: "clang"
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/bin/clang-scan-deps.exe"
      CMAKE_CXX_COMPILER_TARGET: "aarch64-none-linux-android31"
      CMAKE_C_COMPILER_TARGET: "aarch64-none-linux-android31"
      CMAKE_C_FLAGS: "-g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security "
      CMAKE_C_FLAGS_DEBUG: "-fno-limit-debug-info "
      CMAKE_EXE_LINKER_FLAGS: "-static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments  "
      CMAKE_POSITION_INDEPENDENT_CODE: "TRUE"
      CMAKE_SYSROOT: "C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot"
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/tzuri/OneDrive/Desktop/PAN/android/llama-lib/.cxx/Release/6w3f313v/arm64-v8a/CMakeFiles/CMakeScratch/TryCompile-cu7igw'
        
        Run Build Command(s): C:\\Users\\tzuri\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe -v cmTC_94620
        [1/2] C:\\Users\\tzuri\\AppData\\Local\\Android\\Sdk\\ndk\\27.0.12077973\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang.exe --target=aarch64-none-linux-android31 --sysroot=C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fPIE -MD -MT CMakeFiles/cmTC_94620.dir/testCCompiler.c.o -MF CMakeFiles\\cmTC_94620.dir\\testCCompiler.c.o.d -o CMakeFiles/cmTC_94620.dir/testCCompiler.c.o -c C:/Users/tzuri/OneDrive/Desktop/PAN/android/llama-lib/.cxx/Release/6w3f313v/arm64-v8a/CMakeFiles/CMakeScratch/TryCompile-cu7igw/testCCompiler.c
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && C:\\Users\\tzuri\\AppData\\Local\\Android\\Sdk\\ndk\\27.0.12077973\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang.exe --target=aarch64-none-linux-android31 --sysroot=C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments CMakeFiles/cmTC_94620.dir/testCCompiler.c.o -o cmTC_94620  -latomic -lm && cd ."
        FAILED: cmTC_94620 
        C:\\WINDOWS\\system32\\cmd.exe /C "cd . && C:\\Users\\tzuri\\AppData\\Local\\Android\\Sdk\\ndk\\27.0.12077973\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang.exe --target=aarch64-none-linux-android31 --sysroot=C:/Users/tzuri/AppData/Local/Android/Sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/windows-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments CMakeFiles/cmTC_94620.dir/testCCompiler.c.o -o cmTC_94620  -latomic -lm && cd ."
        clang: error: no such file or directory: 'CMakeFiles/cmTC_94620.dir/testCCompiler.c.o'
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
...
